web: gunicorn MOS_ROOT:app

worker: gunicorn configure_foodandbeverage.py
worker: gunicorn configure_hotelDepartment.py
worker: gunicorn configure_hotelrooms.py
worker: gunicorn Fetch_Current_Datetime.py
worker: gunicorn Configure_frontdesk.py
worker: gunicorn GuestDetails.py
worker: gunicorn hotel_contact.py
worker: gunicorn housekeeping_configuration.py
worker: gunicorn Raise_houseKeeping_Request.py
worker: gunicorn Raise_Foodandbeverage_Request.py
worker: gunicorn Raise_Front_Desk_Request.py
worker: gunicorn Reminder_Escalation.py
worker: gunicorn room_configuration.py
worker: gunicorn Signup_Details.py
worker: gunicorn sqlwrapper.py
worker: gunicorn test_File.py
worker: gunicorn configure_laundry.py
worker: gunicorn Raise_Laundry_Request.py
worker: gunicorn Query_all_department_categories.py
worker: gunicorn Configure_Hotelfaq.py
worker: gunicorn reportservicenew.py
worker: gunicorn Query_front_desk_items.py
worker: gunicorn Fetch_Iso_Current_Datetime.py
worker: gunicorn alexa_Notification.py
worker: gunicorn guest_profile.py
